version: "3.5"

services:
  web: #production시에는 image로 변경할 것
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: hub
    ports: 
      - "3000:3000"
    depends_on:
      - db
      - cache
      - mqtt
    network_mode: host
    privileged: true

  db:
    image: jsurf/rpi-mariadb
    restart: always
    container_name: maria
    network_mode: host

    volumes:
      - ./docker/data:/var/lib/maria/data
      - ./sql-scripts:/docker-entrypoint-initdb.d

    #healthcheck를 통해 db컨테이너가 제대로 실행되는지 체크
    #healthcheck:
    #  test: "/usr/bin/mysql --user=user --password=user --execute \"SHOW DATABASES;\""
    #  interval: 3s
    #  timeout: 1s
    #  retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=hub_system
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  cache:
    image: arm32v7/redis
    restart: always
    container_name: redis
    network_mode: host
    ports: 
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

    #healthcheck를 통해 redis 컨테이너가 제대로 실행되는지 체크
    healthcheck: 
      test: "exec 3<> /dev/tcp/127.0.0.1/6379 && echo PING >&3 && head -1 <&3 | grep PONG"
      timeout: 5s
      interval: 5s
      retries: 5
    
  mqtt:
    image: arm32v6/eclipse-mosquitto
    restart: always
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - default
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf